CREATE TABLE IF NOT EXISTS gifts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT,
  imageUrl TEXT,
  active INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS assignments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ipHash TEXT UNIQUE,
  name TEXT,
  telegram TEXT,
  giftId INTEGER,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ipHash TEXT,
  action TEXT,
  ts DATETIME DEFAULT CURRENT_TIMESTAMP
);